version: "3.9"

services:
  app:
    build: .
    container_name: iot-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/iot-db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  db:
    build: ./infra/db
    container_name: iot-db
    ports:
      - "5432:5432"
